### PR TITLE
add DispatchQueue+main

### PR DESCRIPTION
**Pull request by remirobert**
- Add convenient extension for executing code in main thread only if necessary.
- Remove unnecessary assert.

### CODE REVIEW

**Comment by msaps** [comment]
@remirobert ah nice, much cleaner 🎉 any idea why the tests are failing??

**Comment by remirobert** [comment]
strange all passed locally, will check more the reason why.

**Comment by msaps** [comment]
@remirobert seems to be fine after a rebuild 🤷‍♂️

**Comment by RamblinWreck77** [comment]
Small note, I think

```
DispatchQueue.main.async(execute: callback)
```

should be sync not async. The expectation is that the work is performed synchronously *now*, or you sync with the main thread and do xyz before whatever it is you were doing can return/exit scope/move on. Calling .sync is 100% safe because the Thread.mainThread guarantees you're not on the main thread in the first place.

This method, if you are not already on the main thread, might as well be a regular async dispatch. This is fine if all you want to do is check for main thread-edness, but if you need to return work from the main thread (which is unfortunately a pattern we run in to) this falls flat.

**Comment by remirobert** [comment]
@RamblinWreck77 thanks for checking, you are right, since we have the check the dispatch sync will not cause any deadlock.
Please check #195

**Comment by remirobert** [comment]
@msaps probably the CI failed for that reason 😑

**Pull request merged**
