### PR TITLE
execute task in main thread synchronously

### PR DESCRIPTION
**Pull request by remirobert**
Related to #194

### CODE REVIEW

**Comment by RamblinWreck77** [comment]
@remirobert @msaps 

I really liked this extension you made and decided to implement it in our project as it is just so much cleaner then all the Thread.isMainThread checks. In doing so I ran into a few issues and made some small tweaks I think are worth considering:

-The original implementation requires you to capture self (filling your code with either strong self captures *or* weak self and optional chaining) which is unnecessary since this is a synchronous block.

-Sometimes you want to return things from these blocks so we could use a return method. 

```
extension DispatchQueue {

    static func mainThreadDo(callback: () -> Void) {
        if Thread.isMainThread {
            callback()
        } else {
            DispatchQueue.main.sync {
                callback()
            }
        }
    }

    static func mainThreadReturn<T>(callback: () -> T) -> T {
        if Thread.isMainThread {
            return callback()
        } else {
            var result: T!
            DispatchQueue.main.sync {
                result = callback()
            }
            return result
        }
    }
}
```

This way requires no self capture at all, and in practice looks like:

Logging to Crashlytics:
```
DispatchQueue.mainThreadDo {
    CLSLogv("%@", getVaList([log]))
}
```

Generating a mail controller:
```
let mfController = DispatchQueue.mainThreadReturn(callback: {
    return _generateMailController(subject: subject, addendum: addendum, isSupport: isSupport, screenShot: screenShot)
})
```

**Comment by remirobert** [comment]
@RamblinWreck77 it looks very good thanks for sharing !

**Comment by msaps** [comment]
@remirobert is this good to go now?

**Comment by remirobert** [comment]
@msaps all good

**Comment by msaps** [comment]
Released in [3.0.4](https://github.com/uias/Pageboy/releases/tag/3.0.4) 🚀

**Pull request merged**
