### PR TITLE
Set constraints after addSubview for In-Call StatusBar mode

### PR DESCRIPTION
**Pull request by muukii**
When In-Call StatusBar Mode, UIPageViewController will have Top-margin.
I've moved pinToSuperviewEdges after addSubview.

But, pinToSuperviewEdges always guard-return in existing code.
Do you have any reasons for it?

I've attached screenshots below.
What do you think?

Before

ViewTree has double top-margin.

screen shot 2017-06-29 at 15 05 46

After

ViewTree has single top-margin.

screen shot 2017-06-29 at 15 06 45

simulator screen shot jun 29 2017 15 10 25

### CODE REVIEW

**Comment by msaps** [comment]
@muukii this was definitely a bug introduced in a recent version. Looks like the page view controller wouldn't have been constrained at all, the autoresizing masks will have masked it to a point. 

The guard in the `pinToSuperviewEdges` masked this issue, as the application would have crashed trying to add a constraint with no superview. I'll get this in, and remove the guard. 

Thanks! 👍

**Comment by msaps** [comment]
Now available in [1.3.3](https://github.com/uias/Pageboy/releases/tag/1.3.3) 🎉

**Comment by muukii** [comment]
@msaps Wow, It's good! Thank you!

**Comment by msaps** [comment]
@muukii thank you for helping out! 😄

**Pull request merged**
